[[services]]
internal_port = 7700
protocol = "tcp"

  [services.concurrency]
    type = "requests"
    hard_limit = 25
    soft_limit = 20

  [env]
    MEILI_MASTER_KEY = "MASTER_KEY"

  [[services.ports]]
    handlers = ["tls"]
    port = "443"

  [[services.http_checks]]
    interval = "10s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = "2s"
    tls_skip_verify = true

  #[[mounts]]
  #  source = "meili-data"
  #  destination = "/meili_data"